apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k2
      containers:
      - name: jenkins
        image: registry.t-d-h.net/jenkins:jdk11
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1050
          runAsGroup: 1050
        env:
        - name: JAVA_OPTS
          value: -Dpermissive-script-security.enabled=no_security
        ports:
          - name: http-port
            containerPort: 8080
        volumeMounts:
          - name: jenkins-vol
            mountPath: /var/jenkins_home
        livenessProbe:
          tcpSocket:
            port: 8080
          periodSeconds: 4
          timeoutSeconds: 4
          initialDelaySeconds: 30
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 0.1
            memory: 10Mi
        readinessProbe:
          tcpSocket:
            port: 8080
          periodSeconds: 2
          timeoutSeconds: 1
      volumes:
      - hostPath:
          path: /mnt/kubernetes/jenkins
        name: jenkins-vol
