apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: grafana
namespace: monitor
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: registry.t-d-h.net/grafana/grafana
  newTag: 9.1.0
