apiVersion: v1
kind: Namespace
metadata:
  name: monitor
  labels:
    name: monitor
---
apiVersion: v1
kind: Namespace
metadata:
  name: cicd
  labels:
    name: cicd
---
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    name: app
---
apiVersion: v1
kind: Namespace
metadata:
  name: inf
  labels:
    name: inf