apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: argocd
namespace: cicd
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- applications_crd.yaml
- appprojects_crd.yaml
- applicationsets_crd.yaml
- cm_and_secrets.yaml
- networkpolicy.yaml
- rolebinding.yaml
- roles.yaml
- serviceaccount.yaml
- sts.yaml



