apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: jenkins
namespace: cicd
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: jenkins/jenkins #registry.t-d-h.net/jenkins:jdk11
  newTag: latest-jdk11
