---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault-dev
  name: vault-dev
  namespace: inf
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
    nodePort: 30007
  selector:
    app: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault-dev
  name: vault-dev
  namespace: inf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-dev
  template:
    metadata:
      labels:
        app: vault-dev
    spec:
      serviceAccountName: vault-tokenreview
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k8s-node3v-virt.dev.itim.vn
      containers:
      - env:
        - name: VAULT_API_ADDR
          value: http://127.0.0.1:8200
        - name: VAULT_ADDR
          value: http://127.0.0.1:8200
        - name: TZ
          value: Asia/Ho_Chi_Minh
        - name: keyshareA
          valueFrom:
            secretKeyRef:
              key: keyshareA
              name: vault-dev-keyshares
        - name: keyshareB
          valueFrom:
            secretKeyRef:
              key: keyshareB
              name: vault-dev-keyshares
        - name: keyshareC
          valueFrom:
            secretKeyRef:
              key: keyshareC
              name: vault-dev-keyshares
        image: registry.t-d-h.net/vault:1.13.2
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -c
              - |-
                vault operator unseal $keyshareA; vault operator unseal $keyshareB; vault operator unseal $keyshareC;
        command: ["/bin/sh","-c"]
        args:
          - |
            vault server -config=/configmap/extraconfig-from-values.hcl;
        name: vault-dev
        ports:
        - containerPort: 8200
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 4
            memory: 128Mi
          requests:
            cpu: 0.1
            memory: 128Mi
        volumeMounts:
        - mountPath: /vault-dev
          name: vault-dev-data
        - name: "config"
          mountPath: "/configmap/extraconfig-from-values.hcl"
          subPath: "extraconfig-from-values.hcl"
      volumes:
      - hostPath:
          path: /mnt/kubernetes/vault
        name: vault-dev-data
      - name: "config"
        configMap:
          name: "vault-config"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-dev
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: vault-dev
  namespace: inf
spec:
  rules:
  - host: dev-vault.itim.vn
    http:
      paths:
      - path: /
        backend:
          service:
            name: vault-dev
            port:
              number: 8200
        pathType: Prefix
  tls:
  - hosts:
    - dev-vault.itim.vn
    secretName: itim-wildcard-tls
